using SheetsLocalization.Editor.Types;
using UnityEditor.Localization;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Tables;
using UnityEditor;
using UnityEditor.AddressableAssets;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Linq;

namespace SheetsLocalization.Editor.Services
{
    public class AudioLocalizationUpdateService
    {
        public AssetTableCollection EnsureAudioAssetTableCollection(AssetTableCollection existingCollection, string collectionName, string tablePath)
        {
            if (existingCollection != null)
            {
                return existingCollection;
            }

            if (string.IsNullOrWhiteSpace(collectionName))
            {
                collectionName = "AutoGeneratedAudioLocalizationTable";
            }

            var foundCollection = FindExistingAssetTableCollection(collectionName);
            if (foundCollection != null)
            {
                Debug.Log($"Found existing AssetTableCollection: {foundCollection.TableCollectionName}");
                return foundCollection;
            }

            Directory.CreateDirectory(tablePath);
            var createdCollection = LocalizationEditorSettings.CreateAssetTableCollection(collectionName, tablePath);
            if (createdCollection != null)
            {
                Debug.Log($"Created new AssetTableCollection: {collectionName} in {tablePath}");
                EditorUtility.SetDirty(createdCollection);
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
            }
            return createdCollection;
        }

        public Dictionary<string, AudioClip> LoadAudioClipsFromDirectory(string audioDirectory)
        {
            var audioClips = new Dictionary<string, AudioClip>();

            if (!Directory.Exists(audioDirectory))
            {
                Debug.LogWarning($"Audio directory not found: {audioDirectory}");
                return audioClips;
            }

            var audioExtensions = new[] { "*.mp3", "*.wav", "*.ogg", "*.m4a", "*.aac", "*.flac" };

            foreach (var pattern in audioExtensions)
            {
                var files = Directory.GetFiles(audioDirectory, pattern, SearchOption.AllDirectories);
                foreach (var file in files)
                {
                    var fileName = Path.GetFileNameWithoutExtension(file);
                    var relativePath = Path.GetRelativePath(Application.dataPath, file);
                    var assetPath = "Assets/" + relativePath.Replace('\\', '/');

                    var audioClip = AssetDatabase.LoadAssetAtPath<AudioClip>(assetPath);
                    if (audioClip != null)
                    {
                        audioClips[fileName] = audioClip;
                    }
                    else
                    {
                        Debug.LogWarning($"Failed to load audio clip: {assetPath}");
                    }
                }
            }

            Debug.Log($"Loaded {audioClips.Count} audio clips from {audioDirectory}");
            return audioClips;
        }

        public AssetTableData UpdateAudioTableData(AssetTableData assetTableData, Dictionary<string, AudioClip> audioClips, string tablePath, string bundleName = null, bool removeObsoleteEntries = false)
        {
            if (audioClips == null || audioClips.Count == 0)
            {
                Debug.LogWarning("Audio clip list is empty. Audio table update skipped to avoid data loss.");
                return assetTableData;
            }

            var result = UpdateAudioTableDataInternal(assetTableData, audioClips, tablePath, bundleName, removeObsoleteEntries);
            return result;
        }

        private AssetTableCollection FindExistingAssetTableCollection(string collectionName)
        {
            try
            {
                var allCollections = LocalizationEditorSettings.GetAssetTableCollections();

                foreach (var collection in allCollections)
                {
                    if (collection.TableCollectionName == collectionName)
                    {
                        return collection;
                    }
                }

                return null;
            }
            catch (System.Exception ex)
            {
                Debug.LogWarning($"Failed to find existing AssetTableCollection: {ex.Message}");
                return null;
            }
        }

        private AssetTableData UpdateAudioTableDataInternal(AssetTableData assetTableData, Dictionary<string, AudioClip> audioClips, string tablePath, string bundleName = null, bool removeObsoleteEntries = false)
        {
            var updatedData = UpdateLocalizedAssetTable(assetTableData, audioClips, tablePath, bundleName, removeObsoleteEntries);
            Debug.Log("Audio localization updated successfully.");
            return updatedData;
        }

        private AssetTableData UpdateLocalizedAssetTable(AssetTableData assetTableData, Dictionary<string, AudioClip> audioClips, string tablePath, string bundleName = null, bool removeObsoleteEntries = false)
        {
            var assetTableCollection = assetTableData.Table;

            var audioKeysByLocale = ExtractAudioKeysFromFileNames(audioClips);
            if (audioKeysByLocale.Count == 0)
            {
                Debug.LogWarning("Could not extract any audio keys from file names. Update skipped without clearing the existing table. Check the 'key_locale' naming format (e.g. '1_en').");
                return assetTableData;
            }

            if (assetTableCollection == null)
            {
                assetTableCollection = EnsureAudioAssetTableCollection(null, assetTableData.Data.TableName, tablePath);
                if (assetTableCollection == null)
                {
                    Debug.LogError("Failed to create a new AssetTableCollection");
                    return assetTableData;
                }
                Debug.Log($"Created new AssetTableCollection: {assetTableCollection.TableCollectionName}");
            }

            var updateResults = UpdateCollectionIncrementally(assetTableCollection, audioKeysByLocale, tablePath, removeObsoleteEntries);
            Debug.Log($"Update finished: {updateResults.AddedEntries} added, {updateResults.UpdatedEntries} updated, {updateResults.RemovedEntries} removed");

            RemoveAssetsFromAddressables(audioClips.Values);

            EditorUtility.SetDirty(assetTableCollection.SharedData);
            foreach (var table in assetTableCollection.AssetTables)
            {
                EditorUtility.SetDirty(table);
            }

            if (!string.IsNullOrEmpty(bundleName))
            {
                var bundleAssignmentService = new AssetBundleAssignmentService();
                bundleAssignmentService.AssignAddressableGroupToTables(bundleName, null, assetTableCollection);
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            return new AssetTableData
            {
                Table = assetTableCollection,
                Data = assetTableData.Data
            };
        }

        private void RemoveAssetsFromAddressables(IEnumerable<AudioClip> audioClips)
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null) return;

            int removedCount = 0;
            foreach (var clip in audioClips)
            {
                if (clip == null) continue;
                var assetPath = AssetDatabase.GetAssetPath(clip);
                if (string.IsNullOrEmpty(assetPath)) continue;

                var guid = AssetDatabase.AssetPathToGUID(assetPath);
                if (string.IsNullOrEmpty(guid)) continue;

                var entry = settings.FindAssetEntry(guid);
                if (entry != null)
                {
                    settings.RemoveAssetEntry(guid);
                    removedCount++;
                }
            }

            if (removedCount > 0)
            {
                Debug.Log($"Removed {removedCount} audio assets from Addressables");
                AssetDatabase.SaveAssets();
            }
        }

        private Dictionary<string, Dictionary<string, AudioClip>> ExtractAudioKeysFromFileNames(Dictionary<string, AudioClip> audioClips)
        {
            var result = new Dictionary<string, Dictionary<string, AudioClip>>();

            foreach (var audioEntry in audioClips)
            {
                var fileName = audioEntry.Key;
                var audioClip = audioEntry.Value;

                var match = Regex.Match(fileName, @"^(.+?)_([a-z]{2})$");
                if (match.Success)
                {
                    var key = match.Groups[1].Value;
                    var localeCode = match.Groups[2].Value;

                    if (!result.ContainsKey(key))
                    {
                        result[key] = new Dictionary<string, AudioClip>();
                    }

                    result[key][localeCode] = audioClip;
                }
                else
                {
                    Debug.LogWarning($"Could not extract key and locale from file name: {fileName}. Expected format: 'key_locale' (e.g. '1_en')");
                }
            }

            Debug.Log($"Extracted {result.Count} unique audio keys from {audioClips.Count} files");
            return result;
        }

        private Locale GetOrCreateLocale(string localeCode, string tablePath)
        {
            var existingLocales = LocalizationEditorSettings.GetLocales();
            foreach (var locale in existingLocales)
            {
                if (locale.Identifier.Code == localeCode)
                {
                    return locale;
                }
            }

            try
            {
                var systemLanguage = LocaleCodeMapper.ToSystemLanguage(localeCode);
                var newLocale = Locale.CreateLocale(systemLanguage);

                var localesPath = Path.Combine(tablePath, "../Locales");
                var localePath = $"{localesPath}/{localeCode}.asset";
                Directory.CreateDirectory(Path.GetDirectoryName(localePath));
                AssetDatabase.CreateAsset(newLocale, localePath);
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();

                LocalizationEditorSettings.AddLocale(newLocale);

                Debug.Log($"Created new locale: {localeCode} ({newLocale.LocaleName})");
                return newLocale;
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"Failed to create locale '{localeCode}': {ex.Message}");
                return null;
            }
        }

        private EntryUpdateResult UpdateCollectionIncrementally(AssetTableCollection collection, Dictionary<string, Dictionary<string, AudioClip>> newData, string tablePath, bool removeObsoleteEntries = false)
        {
            var results = new EntryUpdateResult();
            var existingKeys = new HashSet<string>();
            if (collection.SharedData.Entries != null)
            {
                foreach (var entry in collection.SharedData.Entries)
                {
                    existingKeys.Add(entry.Key);
                }
            }

            var newKeys = new HashSet<string>(newData.Keys);
            foreach (var audioKeyEntry in newData)
            {
                var entryKey = audioKeyEntry.Key;
                var localeAudioClips = audioKeyEntry.Value;
                var isNewEntry = !existingKeys.Contains(entryKey);
                var wasEntryUpdated = false;

                foreach (var localeEntry in localeAudioClips)
                {
                    var localeCode = localeEntry.Key;
                    var newAudioClip = localeEntry.Value;

                    if (newAudioClip == null)
                        continue;

                    var assetTable = GetOrCreateAssetTableForLocale(collection, localeCode, tablePath);
                    if (assetTable == null)
                    {
                        Debug.LogWarning($"Failed to get or create AssetTable for locale '{localeCode}'");
                        continue;
                    }

                    var entry = assetTable.GetEntry(entryKey);
                    var assetPath = AssetDatabase.GetAssetPath(newAudioClip);
                    if (string.IsNullOrEmpty(assetPath))
                    {
                        Debug.LogError($"Failed to get asset path for audio clip '{newAudioClip.name}'");
                        continue;
                    }

                    var newAssetGuid = AssetDatabase.AssetPathToGUID(assetPath);
                    if (string.IsNullOrEmpty(newAssetGuid))
                    {
                        Debug.LogError($"Failed to get GUID for audio clip '{newAudioClip.name}'");
                        continue;
                    }

                    if (entry == null)
                    {
                        entry = assetTable.AddEntry(entryKey, newAssetGuid);
                        entry.Address = newAssetGuid;
                        if (isNewEntry)
                        {
                            wasEntryUpdated = true;
                        }
                    }
                    else
                    {
                        if (entry.Guid != newAssetGuid)
                        {
                            var oldGuid = entry.Guid;
                            entry.Guid = newAssetGuid;
                            entry.Address = newAssetGuid;
                            wasEntryUpdated = true;
                            Debug.Log($"Updated audio entry '{entryKey}' for locale '{localeCode}': GUID changed from '{oldGuid}' to '{newAssetGuid}'");
                        }
                    }
                }

                if (isNewEntry && wasEntryUpdated)
                {
                    results.AddedEntries++;
                    Debug.Log($"Added new audio entry: '{entryKey}'");
                }
                else if (!isNewEntry && wasEntryUpdated)
                {
                    results.UpdatedEntries++;
                }
            }

            if (removeObsoleteEntries)
            {
                var keysToRemove = existingKeys.Except(newKeys).ToList();
                foreach (var keyToRemove in keysToRemove)
                {
                    RemoveEntryFromAssetCollection(collection, keyToRemove);
                    results.RemovedEntries++;
                    Debug.Log($"Removed obsolete audio entry: '{keyToRemove}'");
                }
            }
            else if (existingKeys.Except(newKeys).Any())
            {
                var obsoleteKeys = existingKeys.Except(newKeys).ToList();
                Debug.LogWarning($"Found {obsoleteKeys.Count} obsolete audio entries, but removal is disabled.");
            }

            return results;
        }

        private void RemoveEntryFromAssetCollection(AssetTableCollection collection, string key)
        {
            if (collection == null || string.IsNullOrEmpty(key))
                return;

            collection.RemoveEntry(key);
            foreach (var assetTable in collection.AssetTables)
            {
                var entry = assetTable.GetEntry(key);
                if (entry != null)
                {
                    assetTable.RemoveEntry(key);
                    EditorUtility.SetDirty(assetTable);
                }
            }

            EditorUtility.SetDirty(collection.SharedData);
        }

        private AssetTable GetOrCreateAssetTableForLocale(AssetTableCollection collection, string localeCode, string tablePath)
        {
            foreach (var assetTable in collection.AssetTables)
            {
                if (assetTable.LocaleIdentifier.Code == localeCode)
                {
                    return assetTable;
                }
            }

            var locale = GetOrCreateLocale(localeCode, tablePath);
            if (locale == null)
            {
                Debug.LogError($"Failed to create locale for code '{localeCode}'");
                return null;
            }

            var newTable = collection.AddNewTable(locale.Identifier) as AssetTable;
            if (newTable != null)
            {
                Debug.Log($"Created new AssetTable for locale '{localeCode}' in collection '{collection.TableCollectionName}'");
                EditorUtility.SetDirty(newTable);
                EditorUtility.SetDirty(collection.SharedData);
            }

            return newTable;
        }
    }
}
